### ISSUE TITLE
An expensive query is run on every click

### ISSUE THREAD

**Issue by isosphere** [isosphere/logseq-journals-nextprev#2]
Running these queries fresh on every click is unnecessarily expensive:

https://github.com/isosphere/logseq-journals-nextprev/blob/a7fb8c50167aeee12d658f13b6a3da6cd85068ea/src/App.vue#L23-L59

We need only to cache the result and, if the appropriate hooks are available, hook into new journal creation or existing journal deletion to update the cache.

**Comment by YU000jp** [comment]
There's a callback for that.
```TypeScript
logseq.App.onTodayJournalCreated(({ title }) => {

})
```
May need to update the version of the plugin API "@logseq/lib" from 0.0.15 to 0.0.17 for this to work normally. (package.json & yarm)

**Comment by isosphere** [comment]
> May need to update the version of the plugin API "@logseq/lib" from 0.0.15 to 0.0.17 for this to work normally. (package.json & yarm)

I've done so, but it seems like the hook doesn't fire. Maybe I'm doing something wrong, or maybe "onTodayJournalCreated" refers to a specific type of journal creation (what's "today" mean here?). The hook isn't documented, unfortunately. 

There doesn't seem to be a way to hook into deletion either, so maybe we lack the hooks required to reliably keep the cache updated. I'd rather the plugin behave reliably and a bit slow, than skip to pages that don't exist anymore or miss new ones but do so faster. 

I wonder if the query would be faster if we didn't `(pull ?p [*])` and instead picked and chose exactly what we wanted it to give us? I can try benchmarking that at some point, but the speed isn't bugging me yet with over a thousand journals.

**Comment by YU000jp** [comment]
Sorry. Two hooks caught fire, but it wasn't enough. I also have two years worth of journals accumulated, but the query speed still seems to be fine.

**Comment by YU000jp** [comment]
Instead of "`(pull ?p [*])`" "`(pull ?p [:block/journal-day])`" might be sufficient.

**Comment by isosphere** [comment]
> Instead of "`(pull ?p [*])`" "`(pull ?p [:block/journal-day])`" might be sufficient.

I've benchmarked the `*` query with 100 samples, and for my journals it takes about 160 ms to execute the query. 

I didn't have to compile 100 samples to see the difference; I'm immediately and consistently getting 80 ms with your suggested query. I'll implement it permanently, thank you!

A 50% improvement in execution speed is pretty good.

**Comment by YU000jp** [comment]
Great!
