### ISSUE TITLE
Hide the button in conditions where it doesn't work

### ISSUE THREAD

**Issue by YU000jp** [isosphere/logseq-journals-nextprev#5]
There's no point in pushing buttons that don't work. Use CSS to hide buttons when non-journal page is open. I can make a pull request.

**Comment by isosphere** [comment]
I don't want the buttons on my toolbar to disappear and re-appear based on context, but I would settle for some kind of indication that they are disabled, if such a thing is possible. 

The buttons are added here:

https://github.com/isosphere/logseq-journals-nextprev/blob/d94fe7fbaacb9619dd5b63cec86986c035684399/src/main.js#L41-L60

... which is done at the applications initialization - this only occurs on the first load. I'm not sure what kind of reactivity we can embed here, but it's probably possible with enough complexity. 

If I can find a way to "dim" the buttons to visually indicate they are disabled without drastically increasing the complexity of the code, I will do so. Any specific suggestions on how to implement this would be welcome.

**Comment by isosphere** [comment]
Closed by #6
