### ISSUE TITLE
Add hotkey option for jumping to previous/next day

### ISSUE THREAD

**Issue by sitaktif** [isosphere/logseq-journals-nextprev#8]
It would be great to have options to add hotkeys to jump to the previous and next day.

**Comment by isosphere** [comment]
Here's how the logseq-journals-calendar handles a string hotkey setting:

https://github.com/xyhp915/logseq-journals-calendar/blob/8f2385cec8db180c4af06e757d25d790b7c0bebd/src/main.js#L133-L146

We could implement two new settings like this and implement it much the same way. I wish we didn't have to type a string for the hotkey, but I'm not aware of a better way to do it. There's no "key" type for a setting, or a key registry system in the API AFAIK.

**Comment by isosphere** [comment]
This is implemented in 1.3.0.
